# Generated by Django 3.1.1 on 2020-09-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp', models.TextField(blank=True, default=None, max_length=30, null=True)),
                ('entered_at', models.TextField(blank=True, default=None, max_length=30, null=True)),
            ],
        ),
    ]
