# Generated by Django 3.0.8 on 2020-08-06 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20200805_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='computation',
            name='updated_at',
        ),
    ]
