# Generated by Django 3.0.8 on 2020-08-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_auto_20200806_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='computation',
            name='entered_at',
            field=models.DateTimeField(null=True),
        ),
    ]
