# Generated by Django 3.0.8 on 2020-08-06 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_computation_entered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computation',
            name='entered_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
